const LOGIN = {
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  FAILURE: 'LOGIN_FAILURE',
};

const LOGOUT = {
  LOGOUT: 'LOGOUT',
};

const ORDER = {
  INFO_UPDATE: 'INFO_UPDATE',
};

export {LOGIN, LOGOUT, ORDER};
